version: '2.0.{build}'
skip_non_tags: true 
image: Visual Studio 2017
environment:
  my_secret:
    secure: Ua7qJynnwt4TrvwtNDFQUA== # Encriptada em https://ci.appveyor.com/tools/encrypt
branches:
  only:
  - master
configuration: Release
install:
  - cmd: dotnet restore
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
build:
  verbosity: minimal
  project: Utilzao.sln
build_script:
  - cmd: dotnet build
  - ps: iex ((New-Object Net.WebClient).DownloadString('https://raw.githubusercontent.com/appveyor/secure-file/master/install.ps1'))
  - cmd: appveyor-tools\secure-file -decrypt Utilzao.Tests\bin\Release\netcoreapp2.1\appsettings.json.enc -secret %my_secret%
  - cmd: dotnet pack
  - cmd: cd Utilzao.Tests
  - cmd: dotnet test
artifacts:
  - path: '**\Utilzao*.nupkg'
    name: UtilzaoNuGet
deploy:
  # NuGet
  - provider: NuGet
    api_key:
      secure: ty/C9+zIqbXaj8BRG+aiDTMHgfdz9NMXjEVaOuQ/SjwHzhEjJpf+3QHKRwPTSceX # your encrypted token from Nuget
    skip_symbols: false
    artifact: UtilzaoNuGet
on_success:
  - echo Processo finalizado com sucesso!